services:
  - type: web
    name: pizzeria-lastoria
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: sql7.freesqldatabase.com
      - key: DB_USER
        value: sql7748578
      - key: DB_PASSWORD
        value: taIVSCuIAz
      - key: DB_NAME
        value: sql7748578
      - key: DB_PORT
        value: 3306 