INSERT INTO dostawaweekday_mp ( nazwa, ulica, ilosc, koszt)
VALUES
( 'Krosno', 'Dębowa', 2, 4),
( 'Krosno', 'Dębowa', 3, 3),
( 'Krosno', 'Handlowa', 2, 4),
( 'Krosno', 'Handlowa', 3, 3),
( 'Krosno', 'Polna', 2, 4),
( 'Krosno', 'Polna', 3, 3),
( 'Krosno', 'Bolesława Prusa', 2, 4),
( 'Krosno', 'Bolesława Prusa', 3, 3),
( 'Krosno', 'Żniwna', 2, 4),
( 'Krosno', 'Żniwna', 3, 3),
( 'Krosno', 'Władysława Stanisława Reymonta', 2, 4),
( 'Krosno', 'Władysława Stanisława Reymonta', 3, 3),
( 'Krosno', 'Nad Badoniem', 2, 4),
( 'Krosno', 'Nad Badoniem', 3, 3),
( 'Krosno', 'Grunwaldzka', 2, 4),
( 'Krosno', 'Grunwaldzka', 3, 3),
( 'Krosno', 'Stanisława Pigonia', 2, 4),
( 'Krosno', 'Stanisława Pigonia', 3, 3),
( 'Krosno', 'Suchodolska', 1, 4),
( 'Krosno', 'Suchodolska', 2, 3),
( 'Krosno', 'Suchodolska', 3, 2);
